window.NEARO_CONFIG = {
  GOOGLE_MAPS_API_KEY: "YOUR_GOOGLE_MAPS_API_KEY",
  SUPABASE_URL: "YOUR_SUPABASE_PROJECT_URL",
  SUPABASE_PUBLISHABLE_KEY: "YOUR_SUPABASE_PUBLISHABLE_KEY",
  SUPABASE_SERVICE_ROLE_KEY: "YOUR_LOCAL_ONLY_SUPABASE_SERVICE_ROLE_KEY",
  TICKETMASTER_CONSUMER_KEY: "YOUR_TICKETMASTER_CONSUMER_KEY",
  GEMINI_API_KEY: "YOUR_LOCAL_ONLY_GEMINI_API_KEY",
};
